version: '3.7'

networks:
  local: 
    name: local
    driver: bridge

services:
  kafdrop:
    image: obsidiandynamics/kafdrop:3.31.0
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka
    networks:
      - local
  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - local
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - local
  nimbus:
    image: storm:2.4.0
    platform: linux/x86_64
    container_name: nimbus
    command: storm nimbus -c topology.worker.max.heap.size.mb=65536 -c worker.heap.memory.mb=65536
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
      - 8080:8080
    volumes:
      - ./storm-conf:/conf
    networks:
      - local

  supervisor:
    image: storm:2.4.0
    platform: linux/x86_64
    container_name: supervisor
    command: storm supervisor -c worker.heap.memory.mb=65536 -c supervisor.memory.capacity.mb=262144 -c worker.profiler.enabled=true
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    volumes:
      - ./storm-conf:/conf
    restart: always
    networks:
      - local
