version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - local
  kafka:
    image: wurstmeister/kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    networks:
      - local
  nimbus:
    image: storm
    command: storm nimbus
    restart: always
    ports:
      - "6627:6627"
    links:
      - zookeeper:zookeeper
    networks:
      - local
  supervisor:
    image: wurstmeister/storm-supervisor
    restart: always
    ports:
      - "8000"
    links:
      - nimbus:nimbus
      - zookeeper:zookeeper
    networks:
      - local
  stormui:
    image: wurstmeister/storm-ui
    restart: always
    ports:
      - "8080:8080"
    links:
      - nimbus:nimbus
      - zookeeper:zookeeper
    networks:
      - local
networks:
  local: 
    name: local
