version: '3.7'

networks:
  local: 
    name: local
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - local
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - local
  nimbus:
    image: storm:2.4.0
    platform: linux/x86_64
    container_name: nimbus
    command: storm nimbus -c topology.worker.max.heap.size.mb=65536 -c worker.heap.memory.mb=65536
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
      - 8080:8080
    volumes:
      - ./storm-conf:/conf
    networks:
      - local

  supervisor:
    image: storm:2.4.0
    platform: linux/x86_64
    container_name: supervisor
    command: storm supervisor -c worker.heap.memory.mb=65536 -c supervisor.memory.capacity.mb=262144 -c worker.profiler.enabled=true
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    volumes:
      - ./storm-conf:/conf
    restart: always
    networks:
      - local
